#=======================================
# Format
#---------------------------------------
#
# <controller_name>:
#   <action_name>:
#     - <role>
#     ...
#     - <role>
#   <action_name>:
#     - <role>
#     ...
#     - <role>
#   ...
# <controller_name>:
#   ...
#
#=======================================
# Example
#---------------------------------------
#
# authors:       # AuthorsController
#   create:      # :create method
#     - manager  # "manager" role
#   show:
#     - manager
#     - admin
#     - user
#   update:
#     - manager
#   destroy:
#     - manager
# books:
#   create:
#     - manager
#   show:
#     - manager
#     - admin
#     - user
#   update:
#     - manager
#   destroy:
#     - manager
#

default: &controller_default
  index: &action_default
    - unauthenticated
    - user
  create:
    *action_default
  new:
    *action_default
  edit:
    *action_default
  show:
    *action_default
  update:
    *action_default
  destroy:
    *action_default

errors:
  routing_error:
    *action_default

pons_api:
  create_user:
    *action_default 
  create_user:
    *action_default
  show_my_info:
    *action_default
  show_user:
    *action_default
  update_user:
    *action_default 
  create_user_image:
    *action_default 
  create_user_header_image:
    *action_default
  index_work_created_by_user:
    *action_default
  index_good_by_user:
    *action_default 
  create_work:
    *action_default 
  show_work:
    *action_default 
  update_work:
    *action_default 
  create_work_image:
    *action_default 
  show_work_image:
    *action_default 
  update_work_image:
    *action_default 
  delete_work_image:
    *action_default 
  create_work_piece:
    *action_default 
  update_work_piece:
    *action_default 
  delete_cleation_piece:
    *action_default 
  create_work_tag:
    *action_default 
  delete_work_tag:
    *action_default 
  create_work_comment:
    *action_default 
  create_good:
    *action_default 
  delete_good:
    *action_default
