#=======================================
# Format
#---------------------------------------
#
# <controller_name>:
#   <action_name>:
#     - <role>
#     ...
#     - <role>
#   <action_name>:
#     - <role>
#     ...
#     - <role>
#   ...
# <controller_name>:
#   ...
#
#=======================================
# Example
#---------------------------------------
#
# authors:       # AuthorsController
#   create:      # :create method
#     - manager  # "manager" role
#   show:
#     - manager
#     - admin
#     - user
#   update:
#     - manager
#   destroy:
#     - manager
# books:
#   create:
#     - manager
#   show:
#     - manager
#     - admin
#     - user
#   update:
#     - manager
#   destroy:
#     - manager
#

default: &controller_default
  index: &action_default
    - unauthenticated
    - user
  create:
    *action_default
  new:
    *action_default
  edit:
    *action_default
  show:
    *action_default
  update:
    *action_default
  destroy:
    *action_default

errors:
  routing_error:
    *action_default

core_api:
  create_user:
    *action_default 
  create_site_user:
    *action_default 
  show_site_user:
    *action_default 
  update_site_user:
    *action_default 
  create_site_user_image:
    *action_default 
  create_site_user_header_image:
    *action_default
  index_creation_created_by_user:
    *action_default
  index_good_by_user:
    *action_default 
  create_creation:
    *action_default 
  show_creation:
    *action_default 
  update_creation:
    *action_default 
  create_creation_image:
    *action_default 
  show_creation_image:
    *action_default 
  update_creation_image:
    *action_default 
  delete_creation_image:
    *action_default 
  create_creation_piece:
    *action_default 
  update_creation_piece:
    *action_default 
  delete_cleation_piece:
    *action_default 
  create_creation_tag:
    *action_default 
  delete_creation_tag:
    *action_default 
  create_creation_comment:
    *action_default 
  create_good:
    *action_default 
  delete_good:
    *action_default
